# Generated by Django 5.2.7 on 2025-10-22 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em Andamento', 'Em Andamento'), ('Resolvida', 'Resolvida'), ('Fechada', 'Fechada')], default='Aberta', max_length=50)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Média', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('memorando', models.FileField(blank=True, null=True, upload_to='memorandos/')),
                ('notas_resolucao', models.TextField(blank=True, null=True)),
                ('avaliacao_estrelas', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('observacao_final', models.TextField(blank=True, null=True)),
                ('nome_cliente_final', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_cliente_final', models.CharField(blank=True, max_length=100, null=True)),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('tecnicos_designados', models.ManyToManyField(blank=True, related_name='chamados_designados', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='chamados.unidade')),
            ],
            options={
                'ordering': ['-data_abertura'],
            },
        ),
    ]
